let sosaData = [
  { id: 1, title: "Bang", album: "Bang", release_year: 2011 },
  { id: 2, title: "I Don't Like", album: "Back from the Dead", release_year: 2012 },
  { id: 3, title: "Love Sosa", album: "Finally Rich", release_year: 2012 },
  { id: 4, title: "Hate Bein' Sober", album: "Finally Rich", release_year: 2012 },
  { id: 5, title: "3Hunna", album: "Finally Rich", release_year: 2012 },
  { id: 6, title: "Kay Kay", album: "Finally Rich", release_year: 2012 },
  { id: 7, title: "No Tomorrow", album: "Finally Rich", release_year: 2012 },
  { id: 8, title: "Citgo", album: "Almighty So", release_year: 2013 },
  { id: 9, title: "Kobe", album: "Almighty So", release_year: 2013 },
  { id: 10, title: "Macaroni Time", album: "Almighty So", release_year: 2013 },
  { id: 11, title: "Almighty So", album: "Almighty So", release_year: 2013 },
  { id: 12, title: "Love No Thotties", album: "Single", release_year: 2013 },
  { id: 13, title: "Ballin'", album: "Bang 2", release_year: 2013 },
  { id: 14, title: "Don't Make No Sense", album: "Bang 2", release_year: 2013 },
  { id: 15, title: "Blew My High", album: "Back from the Dead 2", release_year: 2014 },
  { id: 16, title: "Monster", album: "Back from the Dead 2", release_year: 2014 },
  { id: 17, title: "Faneto", album: "Sorry 4 the Weight", release_year: 2015 },
  { id: 18, title: "Earned It", album: "Sorry 4 the Weight", release_year: 2015 },
  { id: 19, title: "Wassup", album: "Sorry 4 the Weight", release_year: 2015 },
  { id: 20, title: "I Got", album: "Bang 3", release_year: 2015 },
  { id: 21, title: "Ain’t Missing You", album: "Bang 3", release_year: 2015 },
  { id: 22, title: "Colors", album: "Bang 3", release_year: 2015 },
  { id: 23, title: "Fuck Rehab", album: "Bang 3", release_year: 2015 },
  { id: 24, title: "Sosa Chamberlain", album: "Sorry 4 the Weight", release_year: 2015 },
  { id: 25, title: "Shine", album: "Thot Breaker", release_year: 2017 },
  { id: 26, title: "Save That Shit", album: "Thot Breaker", release_year: 2017 },
  { id: 27, title: "The Talk", album: "Dedication", release_year: 2017 },
  { id: 28, title: "Glory Bridge", album: "Dedication", release_year: 2017 },
  { id: 29, title: "I Know", album: "Dedication", release_year: 2017 },
  { id: 30, title: "Now It's Over", album: "Two Zero One Seven", release_year: 2017 },
  { id: 31, title: "War", album: "The Leek Vol. 3", release_year: 2018 },
  { id: 32, title: "Round Da Rosey", album: "GloToven", release_year: 2019 },
  { id: 33, title: "Sky Say", album: "GloToven", release_year: 2019 }
];


module.exports = { sosaData }